"""
Django settings for zyklus_app project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from django.conf.global_settings import CSRF_COOKIE_DOMAIN

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Secret key for Docker
# SECRET_KEY = os.environ['DJANGO_SECRET']
SECRET_KEY = 'django-insecure-d0^)g)s47#m_f55+$)4mbzei#@jvf4ghktd+n*zkc&f+s7(sq0'

# SECURITY WARNING: don't run with debug turned on in production!
# Security for Docker
DEBUG = (bool(int(os.environ.get('DJANGO_DEBUG', 1))))

ALLOWED_HOSTS = []

# CSRF Deploy
CSRF_TRUSTED_ORIGINS = []

if 'DJANGO_CSRF_COOKIE_DOMAIN' in os.environ:
    CSRF_TRUSTED_ORIGINS.append('https://*' + os.environ['DJANGO_CSRF_COOKIE_DOMAIN'])

if 'DJANGO_CSRF_COOKIE_DOMAIN' in os.environ:
    CSRF_COOKIE_DOMAIN = (os.environ['DJANGO_CSRF_COOKIE_DOMAIN'])

# ALLOWED_HOSTS must not be empty if DEBUG == False,
# we set it with an environment-variable
if 'DJANGO_HOST' in os.environ:
    ALLOWED_HOSTS.append(os.environ['DJANGO_HOST'])

# Application definition

# zyklus_app/settings.py
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'questionnaire',
    'member',
    'service',
    'django_crontab',
    'django_bootstrap5',
    'webpush',
    'pwa',
    'extra_views'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zyklus_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zyklus_app.wsgi.application'

# Database Docker
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': os.environ['DB_ENGINE'],
        'NAME': os.environ['MYSQL_DATABASE'],
        'USER': os.environ['MYSQL_USERNAME'],
        'PASSWORD': os.environ['MYSQL_USERPASS'],
        'HOST': os.environ['MYSQL_SERVER'],
        'PORT': os.environ['MYSQL_PORT'],
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'de-DE'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'questionnaire.PseudoUser'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

LOGOUT_REDIRECT_URL = "member:login"

HOME = os.environ['HOME']

# Cron
CRONTAB_COMMAND_PREFIX = "DB_ENGINE=" + os.environ['DB_ENGINE'] + \
                         " MYSQL_SERVER=" + os.environ['MYSQL_SERVER'] + \
                         " MYSQL_PORT=" + os.environ['MYSQL_PORT'] + \
                         " MYSQL_DATABASE=" + os.environ['MYSQL_DATABASE'] + \
                         " MYSQL_USERNAME=" + os.environ['MYSQL_USERNAME'] + \
                         " MYSQL_USERPASS=" + os.environ['MYSQL_USERPASS'] + \
                         " DJANGO_DEBUG=" + os.environ['DJANGO_DEBUG']

CRONJOBS = [
    ('55 21 * * *', 'service.cron.my_scheduled_job', f'>> {HOME}/cron_log.txt 2>&1'),
    ('0 7 * * *', 'service.cron.my_scheduled_job_1', f'>> {HOME}/cron_log.txt 2>&1'),
    ('0 17 * * *', 'service.cron.my_scheduled_job_1', f'>> {HOME}/cron_log.txt 2>&1'),
]

# Web-push
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BA9LhuPa1jv1CSCLucsNMoHUaKDoIvUAoxj0lk3PVEe8N96HXNe83jJfJrjHCNlNMYCN0a_IXF1tWaMsWDiF25g",
    "VAPID_PRIVATE_KEY": "QPW0b-30xfGA26Bo5xmWNobGLSDaaYx0UYFcrJdr9sc",
    "VAPID_ADMIN_EMAIL": "maximilian.rupprecht@stud.th-luebeck.de"
}

# Pwa
PWA_APP_NAME = 'Zyklus-App'
PWA_APP_DESCRIPTION = "Thank you for participating"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/images/lotus.png',
        'sizes': '160x160'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/images/my_apple_icon.png',
        'sizes': '160x160'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/images/icons/splash-640x1136.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
