# Generated by Django 4.0.3 on 2022-05-21 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pseudouser',
            name='questionnaire_end',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaireend'),
        ),
        migrations.AddField(
            model_name='pseudouser',
            name='questionnaire_start',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnairestart'),
        ),
        migrations.AddField(
            model_name='questionnairedaily',
            name='pseudo_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
