# Generated by Django 4.0.3 on 2022-06-14 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pseudouser',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.pair'),
        ),
        migrations.AlterField(
            model_name='pseudouser',
            name='questionnaire_end',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnaireend'),
        ),
        migrations.AlterField(
            model_name='pseudouser',
            name='questionnaire_start',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questionnairestart'),
        ),
    ]
