# Generated by Django 4.0.3 on 2022-05-21 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_pseudouser_questionnaire_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairestart',
            name='question_one',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
