# Generated by Django 4.0.3 on 2022-06-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_questionnairedaily_question_five_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pseudouser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
