# Generated by Django 4.0.3 on 2022-06-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_alter_pseudouser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pseudouser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pseudouser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
