# Generated by Django 4.0.3 on 2022-06-14 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_alter_pseudouser_pair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pseudouser',
            name='questionnaire_end',
        ),
        migrations.RemoveField(
            model_name='pseudouser',
            name='questionnaire_start',
        ),
        migrations.AddField(
            model_name='questionnaireend',
            name='pseudo_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnairestart',
            name='pseudo_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
