# Generated by Django 4.0.3 on 2022-06-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_questionnairedaily_date_questionnaireend_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairedaily',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questionnaireend',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questionnairestart',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
