# Generated by Django 4.0.3 on 2022-06-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_alter_questionnairedaily_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pseudouser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Null', max_length=6, null=True),
        ),
    ]
