# Generated by Django 4.0.3 on 2022-06-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_pseudouser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='ident',
            field=models.CharField(max_length=10, verbose_name='Paar'),
        ),
        migrations.AlterField(
            model_name='pseudouser',
            name='gender',
            field=models.CharField(choices=[('male', 'Männlich'), ('female', 'Weiblich'), ('other', 'Divers')], default='Null', max_length=6, null=True, verbose_name='Geschlecht'),
        ),
    ]
