# Generated by Django 4.0.3 on 2022-06-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_alter_pseudouser_pair'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pair',
            options={'verbose_name': 'Paar'},
        ),
    ]
