# Generated by Django 4.0.3 on 2022-06-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_alter_pair_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pair',
            options={},
        ),
    ]
